// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VisuFiscalHub.Infrastructure.Persistence;

#nullable disable

namespace VisuFiscalHub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260515124342_AddIndPresencaToDocumentoFiscal")]
    partial class AddIndPresencaToDocumentoFiscal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VisuFiscalHub.Domain.Entities.ClienteApp", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("client_id");

                    b.Property<string>("ClientSecretHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("client_secret_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<byte[]>("WebhookSecretCriptografado")
                        .HasColumnType("bytea")
                        .HasColumnName("webhook_secret_criptografado");

                    b.Property<string>("WebhookUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("webhook_url");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique()
                        .HasDatabaseName("ix_cliente_apps_client_id");

                    b.ToTable("cliente_apps", (string)null);
                });

            modelBuilder.Entity("VisuFiscalHub.Domain.Entities.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<Guid>("DocumentoFiscalId")
                        .HasColumnType("uuid")
                        .HasColumnName("documento_fiscal_id");

                    b.Property<long>("ElapsedMs")
                        .HasColumnType("bigint")
                        .HasColumnName("elapsed_ms");

                    b.Property<string>("ResponseCode")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("response_code");

                    b.Property<string>("ResponseMessage")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("response_message");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.Property<int>("TipoTentativa")
                        .HasColumnType("integer")
                        .HasColumnName("tipo_tentativa");

                    b.HasKey("Id");

                    b.HasIndex("DocumentoFiscalId")
                        .HasDatabaseName("ix_delivery_attempts_documento_fiscal_id");

                    b.ToTable("delivery_attempts", (string)null);
                });

            modelBuilder.Entity("VisuFiscalHub.Domain.Entities.DocumentoFiscal", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AuthorizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("authorized_at");

                    b.Property<string>("ChaveAcesso")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("character varying(44)")
                        .HasColumnName("chave_acesso");

                    b.Property<Guid>("ClienteAppId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_app_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("idempotency_key");

                    b.Property<int>("IndPresenca")
                        .HasColumnType("integer")
                        .HasColumnName("ind_presenca");

                    b.Property<string>("MotivoRejeicao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("motivo_rejeicao");

                    b.Property<long>("Numero")
                        .HasColumnType("bigint")
                        .HasColumnName("numero");

                    b.Property<string>("Protocolo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("protocolo");

                    b.Property<string>("QrCode")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("qr_code");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("serie");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer")
                        .HasColumnName("tipo");

                    b.Property<string>("XmlAssinado")
                        .HasColumnType("text")
                        .HasColumnName("xml_assinado");

                    b.HasKey("Id");

                    b.HasIndex("ChaveAcesso")
                        .HasDatabaseName("ix_documentos_fiscais_chave_acesso");

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_documentos_fiscais_status_created_at");

                    b.HasIndex("TenantId", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ix_documentos_fiscais_tenant_idempotency");

                    b.ToTable("documentos_fiscais", (string)null);
                });

            modelBuilder.Entity("VisuFiscalHub.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CIdToken")
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("c_id_token");

                    b.Property<byte[]>("CertificadoPfxCriptografado")
                        .HasColumnType("bytea")
                        .HasColumnName("certificado_pfx_criptografado");

                    b.Property<byte[]>("CertificadoSenhaCriptografada")
                        .HasColumnType("bytea")
                        .HasColumnName("certificado_senha_criptografada");

                    b.Property<DateTimeOffset?>("CertificadoVencimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("certificado_vencimento");

                    b.Property<Guid>("ClienteAppId")
                        .HasColumnType("uuid")
                        .HasColumnName("cliente_app_id");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("character varying(14)")
                        .HasColumnName("cnpj");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<byte[]>("Csc")
                        .HasColumnType("bytea")
                        .HasColumnName("csc");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("NomeFantasia")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("nome_fantasia");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("razao_social");

                    b.HasKey("Id");

                    b.HasIndex("ClienteAppId")
                        .HasDatabaseName("ix_tenants_cliente_app_id");

                    b.HasIndex("Cnpj", "ClienteAppId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_cnpj_cliente_app_id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("VisuFiscalHub.Infrastructure.Persistence.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt", "OccurredAt")
                        .HasDatabaseName("ix_outbox_messages_processed_at_occurred_at");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("VisuFiscalHub.Domain.Entities.DeliveryAttempt", b =>
                {
                    b.HasOne("VisuFiscalHub.Domain.Entities.DocumentoFiscal", null)
                        .WithMany()
                        .HasForeignKey("DocumentoFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_delivery_attempts_documento_fiscal_id");
                });

            modelBuilder.Entity("VisuFiscalHub.Domain.Entities.DocumentoFiscal", b =>
                {
                    b.HasOne("VisuFiscalHub.Domain.Entities.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_documentos_fiscais_tenant_id");

                    b.OwnsMany("VisuFiscalHub.Domain.Entities.ItemDocumento", "Items", b1 =>
                        {
                            b1.Property<Guid>("DocumentoFiscalId")
                                .HasColumnType("uuid")
                                .HasColumnName("documento_fiscal_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("Numero")
                                .HasColumnType("integer")
                                .HasColumnName("numero");

                            b1.HasKey("DocumentoFiscalId", "Id");

                            b1.ToTable("itens_documento", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DocumentoFiscalId");

                            b1.OwnsOne("VisuFiscalHub.Domain.ValueObjects.Produto", "Produto", b2 =>
                                {
                                    b2.Property<Guid>("ItemDocumentoDocumentoFiscalId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("ItemDocumentoId")
                                        .HasColumnType("integer");

                                    b2.Property<string>("Cest")
                                        .HasMaxLength(7)
                                        .HasColumnType("character varying(7)")
                                        .HasColumnName("produto_cest");

                                    b2.Property<string>("CfopSaida")
                                        .IsRequired()
                                        .HasMaxLength(4)
                                        .HasColumnType("character varying(4)")
                                        .HasColumnName("produto_cfop");

                                    b2.Property<string>("CodigoProduto")
                                        .IsRequired()
                                        .HasMaxLength(60)
                                        .HasColumnType("character varying(60)")
                                        .HasColumnName("produto_codigo");

                                    b2.Property<string>("Descricao")
                                        .IsRequired()
                                        .HasMaxLength(120)
                                        .HasColumnType("character varying(120)")
                                        .HasColumnName("produto_descricao");

                                    b2.Property<string>("Ncm")
                                        .IsRequired()
                                        .HasMaxLength(8)
                                        .HasColumnType("character varying(8)")
                                        .HasColumnName("produto_ncm");

                                    b2.Property<int>("OrigemMercadoria")
                                        .HasColumnType("integer")
                                        .HasColumnName("produto_origem");

                                    b2.Property<decimal>("Quantidade")
                                        .HasPrecision(15, 4)
                                        .HasColumnType("numeric(15,4)")
                                        .HasColumnName("produto_quantidade");

                                    b2.Property<string>("UnidadeComercial")
                                        .IsRequired()
                                        .HasMaxLength(6)
                                        .HasColumnType("character varying(6)")
                                        .HasColumnName("produto_unidade");

                                    b2.Property<decimal>("ValorDesconto")
                                        .HasPrecision(15, 2)
                                        .HasColumnType("numeric(15,2)")
                                        .HasColumnName("produto_valor_desconto");

                                    b2.Property<decimal>("ValorUnitario")
                                        .HasPrecision(21, 10)
                                        .HasColumnType("numeric(21,10)")
                                        .HasColumnName("produto_valor_unitario");

                                    b2.HasKey("ItemDocumentoDocumentoFiscalId", "ItemDocumentoId");

                                    b2.ToTable("itens_documento");

                                    b2.WithOwner()
                                        .HasForeignKey("ItemDocumentoDocumentoFiscalId", "ItemDocumentoId");
                                });

                            b1.OwnsOne("VisuFiscalHub.Domain.ValueObjects.Tributo", "Tributo", b2 =>
                                {
                                    b2.Property<Guid>("ItemDocumentoDocumentoFiscalId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("ItemDocumentoId")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("AliquotaCofins")
                                        .HasPrecision(7, 4)
                                        .HasColumnType("numeric(7,4)")
                                        .HasColumnName("trib_aliquota_cofins");

                                    b2.Property<decimal>("AliquotaIcms")
                                        .HasPrecision(7, 4)
                                        .HasColumnType("numeric(7,4)")
                                        .HasColumnName("trib_aliquota_icms");

                                    b2.Property<decimal>("AliquotaPis")
                                        .HasPrecision(7, 4)
                                        .HasColumnType("numeric(7,4)")
                                        .HasColumnName("trib_aliquota_pis");

                                    b2.Property<decimal>("BaseCalculoCofins")
                                        .HasPrecision(15, 2)
                                        .HasColumnType("numeric(15,2)")
                                        .HasColumnName("trib_base_calculo_cofins");

                                    b2.Property<decimal>("BaseCalculoIcms")
                                        .HasPrecision(15, 2)
                                        .HasColumnType("numeric(15,2)")
                                        .HasColumnName("trib_base_calculo_icms");

                                    b2.Property<decimal>("BaseCalculoPis")
                                        .HasPrecision(15, 2)
                                        .HasColumnType("numeric(15,2)")
                                        .HasColumnName("trib_base_calculo_pis");

                                    b2.Property<int>("CsosnOuCst")
                                        .HasColumnType("integer")
                                        .HasColumnName("trib_csosn_ou_cst");

                                    b2.Property<int>("CstCofins")
                                        .HasColumnType("integer")
                                        .HasColumnName("trib_cst_cofins");

                                    b2.Property<int>("CstPis")
                                        .HasColumnType("integer")
                                        .HasColumnName("trib_cst_pis");

                                    b2.Property<int>("TipoIcms")
                                        .HasColumnType("integer")
                                        .HasColumnName("trib_tipo_icms");

                                    b2.Property<decimal>("ValorCofins")
                                        .HasPrecision(15, 2)
                                        .HasColumnType("numeric(15,2)")
                                        .HasColumnName("trib_valor_cofins");

                                    b2.Property<decimal>("ValorIcms")
                                        .HasPrecision(15, 2)
                                        .HasColumnType("numeric(15,2)")
                                        .HasColumnName("trib_valor_icms");

                                    b2.Property<decimal>("ValorPis")
                                        .HasPrecision(15, 2)
                                        .HasColumnType("numeric(15,2)")
                                        .HasColumnName("trib_valor_pis");

                                    b2.HasKey("ItemDocumentoDocumentoFiscalId", "ItemDocumentoId");

                                    b2.ToTable("itens_documento");

                                    b2.WithOwner()
                                        .HasForeignKey("ItemDocumentoDocumentoFiscalId", "ItemDocumentoId");
                                });

                            b1.Navigation("Produto")
                                .IsRequired();

                            b1.Navigation("Tributo")
                                .IsRequired();
                        });

                    b.OwnsMany("VisuFiscalHub.Domain.ValueObjects.Pagamento", "Pagamentos", b1 =>
                        {
                            b1.Property<Guid>("DocumentoFiscalId")
                                .HasColumnType("uuid")
                                .HasColumnName("documento_fiscal_id");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("TipoPagamento")
                                .HasColumnType("integer")
                                .HasColumnName("tipo_pagamento");

                            b1.Property<decimal>("Valor")
                                .HasPrecision(15, 2)
                                .HasColumnType("numeric(15,2)")
                                .HasColumnName("valor");

                            b1.HasKey("DocumentoFiscalId", "Id");

                            b1.ToTable("pagamentos_documento", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DocumentoFiscalId");
                        });

                    b.Navigation("Items");

                    b.Navigation("Pagamentos");
                });

            modelBuilder.Entity("VisuFiscalHub.Domain.Entities.Tenant", b =>
                {
                    b.HasOne("VisuFiscalHub.Domain.Entities.ClienteApp", null)
                        .WithMany()
                        .HasForeignKey("ClienteAppId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenants_cliente_app_id");

                    b.OwnsOne("VisuFiscalHub.Domain.ValueObjects.ConfiguracaoFiscal", "ConfiguracaoFiscal", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Ambiente")
                                .HasColumnType("integer")
                                .HasColumnName("ambiente");

                            b1.Property<int>("Crt")
                                .HasColumnType("integer")
                                .HasColumnName("crt");

                            b1.Property<string>("Serie")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("serie");

                            b1.Property<int>("UfCodigo")
                                .HasColumnType("integer")
                                .HasColumnName("uf_codigo");

                            b1.HasKey("TenantId");

                            b1.ToTable("tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.OwnsOne("VisuFiscalHub.Domain.ValueObjects.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<Guid>("TenantId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Bairro")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("end_bairro");

                            b1.Property<string>("Cep")
                                .IsRequired()
                                .HasMaxLength(8)
                                .HasColumnType("character varying(8)")
                                .HasColumnName("end_cep");

                            b1.Property<int>("CodigoMunicipio")
                                .HasColumnType("integer")
                                .HasColumnName("end_codigo_municipio");

                            b1.Property<string>("CodigoPais")
                                .IsRequired()
                                .HasMaxLength(4)
                                .HasColumnType("character varying(4)")
                                .HasColumnName("end_codigo_pais");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("end_complemento");

                            b1.Property<string>("Logradouro")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("end_logradouro");

                            b1.Property<string>("Municipio")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("end_municipio");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("end_numero");

                            b1.Property<string>("Telefone")
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("end_telefone");

                            b1.Property<string>("Uf")
                                .IsRequired()
                                .HasMaxLength(2)
                                .HasColumnType("character varying(2)")
                                .HasColumnName("end_uf");

                            b1.HasKey("TenantId");

                            b1.ToTable("tenants");

                            b1.WithOwner()
                                .HasForeignKey("TenantId");
                        });

                    b.Navigation("ConfiguracaoFiscal")
                        .IsRequired();

                    b.Navigation("Endereco")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
