// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotaFiscalHub.Modules.ContasPlanos.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotaFiscalHub.Modules.ContasPlanos.Infrastructure.Migrations
{
    [DbContext(typeof(ContasPlanosDbContext))]
    [Migration("20260703142838_AddOutboxInbox")]
    partial class AddOutboxInbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("contas")
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotaFiscalHub.BuildingBlocks.Messaging.InboxMessage", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<string>("Handler")
                        .HasColumnType("text")
                        .HasColumnName("handler");

                    b.Property<DateTimeOffset>("ProcessadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processada_em");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_evento");

                    b.HasKey("MessageId", "Handler");

                    b.ToTable("inbox", "contas");
                });

            modelBuilder.Entity("NotaFiscalHub.BuildingBlocks.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("ErroUltimo")
                        .HasColumnType("text")
                        .HasColumnName("erro_ultimo");

                    b.Property<DateTimeOffset>("OcorridoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrido_em");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processada_em");

                    b.Property<DateTimeOffset>("ProximaTentativaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("proxima_tentativa_em");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("Tentativas")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_evento");

                    b.HasKey("Id");

                    b.HasIndex("Status", "ProximaTentativaEm")
                        .HasFilter("status = 'Pendente'");

                    b.ToTable("outbox", "contas");
                });
#pragma warning restore 612, 618
        }
    }
}
