// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotaFiscalHub.BuildingBlocks.Idempotency;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotaFiscalHub.BuildingBlocks.Idempotency.Migrations
{
    [DbContext(typeof(IdempotencyDbContext))]
    partial class IdempotencyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotaFiscalHub.BuildingBlocks.Idempotency.IdempotencyRecordEntity", b =>
                {
                    b.Property<Guid>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_id");

                    b.Property<string>("Ambiente")
                        .HasColumnType("text")
                        .HasColumnName("ambiente");

                    b.Property<string>("Rota")
                        .HasColumnType("text")
                        .HasColumnName("rota");

                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("CriadaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criada_em");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<string>("PayloadHashSha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload_hash_sha256");

                    b.Property<string>("RespostaContentType")
                        .HasColumnType("text")
                        .HasColumnName("resposta_content_type");

                    b.Property<string>("RespostaCorpo")
                        .HasColumnType("text")
                        .HasColumnName("resposta_corpo");

                    b.Property<string>("RespostaLocation")
                        .HasColumnType("text")
                        .HasColumnName("resposta_location");

                    b.Property<int?>("RespostaStatus")
                        .HasColumnType("integer")
                        .HasColumnName("resposta_status");

                    b.HasKey("ContaId", "Ambiente", "Rota", "Key");

                    b.HasIndex("ExpiraEm");

                    b.ToTable("idempotency_registro", "kernel");
                });
#pragma warning restore 612, 618
        }
    }
}
