// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NotaFiscalHub.BuildingBlocks.Auditoria;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NotaFiscalHub.BuildingBlocks.Auditoria.Migrations
{
    [DbContext(typeof(AuditoriaDbContext))]
    [Migration("20260704023827_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NotaFiscalHub.BuildingBlocks.Auditoria.RegistroAuditoriaEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("acao");

                    b.Property<string>("Ator")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ator");

                    b.Property<Guid?>("ContaId")
                        .HasColumnType("uuid")
                        .HasColumnName("conta_id");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<string>("Dados")
                        .HasColumnType("jsonb")
                        .HasColumnName("dados");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("OcorridoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrido_em");

                    b.Property<string>("RecursoId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recurso_id");

                    b.Property<string>("RecursoTipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recurso_tipo");

                    b.Property<DateTimeOffset>("RegistradoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registrado_em");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_evento");

                    b.HasKey("Id");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("ux_registro_auditoria_message_id");

                    b.HasIndex("ContaId", "RegistradoEm")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_registro_auditoria_conta_id_registrado_em");

                    b.ToTable("registro_auditoria", "auditoria");
                });
#pragma warning restore 612, 618
        }
    }
}
